### ISSUE TITLE
People struggling to remove this from Chrome

### ISSUE THREAD

**Issue by samjewell** [antijingoist/opendyslexic-chrome#2]
Would be good to address negative reviews on the chrome extensions store by making it easier to uninstall - probably just by adding it to the toolbar as an icon like Wave does.

![screen shot 2015-06-14 at 10 41 22](https://cloud.githubusercontent.com/assets/2903904/8148078/10fdc02e-1282-11e5-93da-d14c86d03c3e.png)

[I'd like to contribute one day - excellent project btw!]

**Comment by RobertJGabriel** [comment]
I have another app similar, but going to close it cause I only discovered you had the code open source :) Will post a pull request in the morning with a turn it on or off button :)

@antijingoist  If thats okay with you ?

https://chrome.google.com/webstore/detail/helper-bird-opendyslexic/ahmapmilbkfamljbpgphfndeemhnajme?hl=en

**Comment by antijingoist** [comment]
I honestly like the on/off button.

Sorry I haven't been around much this year; it was a long one.

I only see one pull request, so I'll pull in Robert's changes. Thanks!
