### ISSUE TITLE
Set to "Off" by default

### ISSUE THREAD

**Issue by searley2** [antijingoist/opendyslexic-chrome#7]
I have this installed on computers for our students in the library, but would like the default setting to be "Off".  So that only the students that want to use it have to turn it on.
##

**Comment by RobertJGabriel** [comment]
Awesome, will have an update out tonight with thanks for the feedback :) @searley2

**Comment by RobertJGabriel** [comment]
@searley2 Thats sorted just waiting for it to be pushed to the store
